// Dados mockados para preview do dashboard
// Use apenas para desenvolvimento/demonstração

export const mockVisaoGeral = {
  total_projetos: 25,
  projetos_concluidos: 10, // PRJ-002, 004, 007, 009, 010, 011, 012, 013, 014, 015
  projetos_em_execucao: 13, // PRJ-001, 005, 006, 016, 017, 018, 019, 020, 021, 022, 023, 024, 025
  projetos_atrasados: 2, // PRJ-003, 008
  percentual_concluido_medio: 67.5,
  total_areas: 45,
  areas_concluidas: 18,
  areas_ativas: 27,
}

export const mockAtrasosEngenheiro = [
  {
    eng_id: '1',
    engenheiro: 'João Silva',
    qtde_projetos_atrasados: 2,
    qtde_areas_atrasadas: 3,
    dias_medios_atraso: 12.5,
    atraso_maximo_dias: 25,
  },
  {
    eng_id: '2',
    engenheiro: 'Maria Santos',
    qtde_projetos_atrasados: 1,
    qtde_areas_atrasadas: 2,
    dias_medios_atraso: 8.0,
    atraso_maximo_dias: 15,
  },
]

export const mockCargaTrabalho = [
  {
    eng_id: '1',
    engenheiro: 'João Silva',
    exclusivo: true,
    dias_estimados_totais: 45,
    percentual_execucao_media: 65.0,
    dias_restantes: 16,
    areas_ativas: 5,
    projetos_ativos: 3,
  },
  {
    eng_id: '2',
    engenheiro: 'Maria Santos',
    exclusivo: false,
    dias_estimados_totais: 38,
    percentual_execucao_media: 72.0,
    dias_restantes: 11,
    areas_ativas: 4,
    projetos_ativos: 2,
  },
  {
    eng_id: '3',
    engenheiro: 'Carlos Oliveira',
    exclusivo: true,
    dias_estimados_totais: 52,
    percentual_execucao_media: 58.0,
    dias_restantes: 22,
    areas_ativas: 6,
    projetos_ativos: 4,
  },
]

export const mockRetrabalhos = [
  {
    eng_id: '1',
    engenheiro: 'João Silva',
    qtde_areas_retrabalho: 2,
    total_retrabalhos: 5,
    horas_trabalhadas_total: 40,
    horas_retrabalho_total: 5,
    retrabalho_medio_percentual: 12.5,
    projetos_com_retrabalho: 2,
  },
  {
    eng_id: '2',
    engenheiro: 'Maria Santos',
    qtde_areas_retrabalho: 1,
    total_retrabalhos: 2,
    horas_trabalhadas_total: 25,
    horas_retrabalho_total: 2,
    retrabalho_medio_percentual: 8.0,
    projetos_com_retrabalho: 1,
  },
]

export const mockProjetosStatus = [
  {
    status: 'Concluído',
    quantidade: 8,
    percentual: 32.0,
  },
  {
    status: 'Em Andamento',
    quantidade: 15,
    percentual: 60.0,
  },
  {
    status: 'Atrasado',
    quantidade: 2,
    percentual: 8.0,
  },
]

export const mockProjetos = [
  {
    projeto_id: '1',
    codigo_projeto: 'PRJ-001',
    cliente: 'Cliente ABC',
    descricao: 'Projeto de instalação elétrica',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Elétrico',
    status_descricao: 'Em Andamento',
    percentual_andamento: 65.0,
    data_inicio: '2024-01-15',
    data_prevista: '2024-03-15',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '2',
    codigo_projeto: 'PRJ-002',
    cliente: 'Cliente XYZ',
    descricao: 'Projeto hidrossanitário completo',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Hidrossanitário',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-10',
    data_prevista: '2024-02-28',
    data_conclusao: '2024-02-25',
    dias_atraso: 0,
  },
  {
    projeto_id: '3',
    codigo_projeto: 'PRJ-003',
    cliente: 'Cliente DEF',
    descricao: 'Estrutural - Fundações',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'Estrutural',
    status_descricao: 'Atrasado',
    percentual_andamento: 45.0,
    data_inicio: '2024-02-01',
    data_prevista: '2024-03-20',
    data_conclusao: null,
    dias_atraso: 12,
  },
  {
    projeto_id: '4',
    codigo_projeto: 'PRJ-004',
    cliente: 'Cliente GHI',
    descricao: 'Climatização - Sistema de ar condicionado',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Climatização',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-05',
    data_prevista: '2024-02-15',
    data_conclusao: '2024-02-10',
    dias_atraso: 0,
  },
  {
    projeto_id: '5',
    codigo_projeto: 'PRJ-005',
    cliente: 'Cliente JKL',
    descricao: 'SPDA - Sistema de proteção contra descargas',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'SPDA',
    status_descricao: 'Em Andamento',
    percentual_andamento: 80.0,
    data_inicio: '2024-02-10',
    data_prevista: '2024-03-30',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '6',
    codigo_projeto: 'PRJ-006',
    cliente: 'Cliente MNO',
    descricao: 'Automação - Sistema inteligente',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'Automação',
    status_descricao: 'Em Andamento',
    percentual_andamento: 55.0,
    data_inicio: '2024-02-20',
    data_prevista: '2024-04-10',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '7',
    codigo_projeto: 'PRJ-007',
    cliente: 'Cliente PQR',
    descricao: 'Prevenção e Combate a Incêndio',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Prevenção e Combate a Incêndio',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-20',
    data_prevista: '2024-03-01',
    data_conclusao: '2024-02-28',
    dias_atraso: 0,
  },
  {
    projeto_id: '8',
    codigo_projeto: 'PRJ-008',
    cliente: 'Cliente STU',
    descricao: 'Gás - Instalação de sistema de gás',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Gás',
    status_descricao: 'Atrasado',
    percentual_andamento: 30.0,
    data_inicio: '2024-02-15',
    data_prevista: '2024-03-25',
    data_conclusao: null,
    dias_atraso: 8,
  },
  // Mais projetos concluídos
  {
    projeto_id: '9',
    codigo_projeto: 'PRJ-009',
    cliente: 'Cliente VWX',
    descricao: 'Telefonia e Dados',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Telefonia e Dados',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-08',
    data_prevista: '2024-02-20',
    data_conclusao: '2024-02-18',
    dias_atraso: 0,
  },
  {
    projeto_id: '10',
    codigo_projeto: 'PRJ-010',
    cliente: 'Cliente YZA',
    descricao: 'Elétrico - Instalação completa',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Elétrico',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-12',
    data_prevista: '2024-02-25',
    data_conclusao: '2024-02-22',
    dias_atraso: 0,
  },
  {
    projeto_id: '11',
    codigo_projeto: 'PRJ-011',
    cliente: 'Cliente BCD',
    descricao: 'Hidrossanitário - Sistema completo',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'Hidrossanitário',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-18',
    data_prevista: '2024-03-05',
    data_conclusao: '2024-03-01',
    dias_atraso: 0,
  },
  {
    projeto_id: '12',
    codigo_projeto: 'PRJ-012',
    cliente: 'Cliente EFG',
    descricao: 'SPDA - Para-raios',
    engenheiro_nome: 'João Silva',
    area_descricao: 'SPDA',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-01-25',
    data_prevista: '2024-03-10',
    data_conclusao: '2024-03-08',
    dias_atraso: 0,
  },
  {
    projeto_id: '13',
    codigo_projeto: 'PRJ-013',
    cliente: 'Cliente HIJ',
    descricao: 'Gás - Sistema completo',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Gás',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-02-05',
    data_prevista: '2024-03-15',
    data_conclusao: '2024-03-12',
    dias_atraso: 0,
  },
  {
    projeto_id: '14',
    codigo_projeto: 'PRJ-014',
    cliente: 'Cliente KLM',
    descricao: 'Climatização - Ar condicionado',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'Climatização',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-02-08',
    data_prevista: '2024-03-20',
    data_conclusao: '2024-03-18',
    dias_atraso: 0,
  },
  {
    projeto_id: '15',
    codigo_projeto: 'PRJ-015',
    cliente: 'Cliente NOP',
    descricao: 'Elétrico - Instalação residencial',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Elétrico',
    status_descricao: 'Concluído',
    percentual_andamento: 100.0,
    data_inicio: '2024-02-12',
    data_prevista: '2024-03-25',
    data_conclusao: '2024-03-23',
    dias_atraso: 0,
  },
  // Mais projetos em execução
  {
    projeto_id: '16',
    codigo_projeto: 'PRJ-016',
    cliente: 'Cliente QRS',
    descricao: 'Hidrossanitário - Reforma',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Hidrossanitário',
    status_descricao: 'Em Andamento',
    percentual_andamento: 70.0,
    data_inicio: '2024-02-18',
    data_prevista: '2024-04-05',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '17',
    codigo_projeto: 'PRJ-017',
    cliente: 'Cliente TUV',
    descricao: 'Estrutural - Reforma estrutural',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'Estrutural',
    status_descricao: 'Em Andamento',
    percentual_andamento: 40.0,
    data_inicio: '2024-02-22',
    data_prevista: '2024-04-15',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '18',
    codigo_projeto: 'PRJ-018',
    cliente: 'Cliente WXY',
    descricao: 'Automação - Casa inteligente',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Automação',
    status_descricao: 'Em Andamento',
    percentual_andamento: 60.0,
    data_inicio: '2024-02-25',
    data_prevista: '2024-04-20',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '19',
    codigo_projeto: 'PRJ-019',
    cliente: 'Cliente ZAB',
    descricao: 'Telefonia - Infraestrutura',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Telefonia e Dados',
    status_descricao: 'Em Andamento',
    percentual_andamento: 50.0,
    data_inicio: '2024-03-01',
    data_prevista: '2024-04-25',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '20',
    codigo_projeto: 'PRJ-020',
    cliente: 'Cliente CDE',
    descricao: 'Climatização - Sistema VRF',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'Climatização',
    status_descricao: 'Em Andamento',
    percentual_andamento: 75.0,
    data_inicio: '2024-03-05',
    data_prevista: '2024-04-30',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '21',
    codigo_projeto: 'PRJ-021',
    cliente: 'Cliente FGH',
    descricao: 'Elétrico - Comercial',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Elétrico',
    status_descricao: 'Em Andamento',
    percentual_andamento: 85.0,
    data_inicio: '2024-03-08',
    data_prevista: '2024-05-05',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '22',
    codigo_projeto: 'PRJ-022',
    cliente: 'Cliente IJK',
    descricao: 'Hidrossanitário - Predial',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Hidrossanitário',
    status_descricao: 'Em Andamento',
    percentual_andamento: 35.0,
    data_inicio: '2024-03-10',
    data_prevista: '2024-05-10',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '23',
    codigo_projeto: 'PRJ-023',
    cliente: 'Cliente LMN',
    descricao: 'SPDA - Edifício',
    engenheiro_nome: 'Carlos Oliveira',
    area_descricao: 'SPDA',
    status_descricao: 'Em Andamento',
    percentual_andamento: 90.0,
    data_inicio: '2024-03-12',
    data_prevista: '2024-05-15',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '24',
    codigo_projeto: 'PRJ-024',
    cliente: 'Cliente OPQ',
    descricao: 'Prevenção Incêndio - Sistema completo',
    engenheiro_nome: 'João Silva',
    area_descricao: 'Prevenção e Combate a Incêndio',
    status_descricao: 'Em Andamento',
    percentual_andamento: 45.0,
    data_inicio: '2024-03-15',
    data_prevista: '2024-05-20',
    data_conclusao: null,
    dias_atraso: 0,
  },
  {
    projeto_id: '25',
    codigo_projeto: 'PRJ-025',
    cliente: 'Cliente RST',
    descricao: 'Automação - Predial',
    engenheiro_nome: 'Maria Santos',
    area_descricao: 'Automação',
    status_descricao: 'Em Andamento',
    percentual_andamento: 25.0,
    data_inicio: '2024-03-18',
    data_prevista: '2024-05-25',
    data_conclusao: null,
    dias_atraso: 0,
  },
]

export const mockEngenheiros = [
  {
    eng_id: '1',
    nome: 'João Silva',
    exclusivo: true,
    total_projetos: 8,
    areas_ativas: 5,
    media_percentual: 72.5,
    total_retrabalhos: 3,
    dias_trabalho_pendentes: 25,
    areas_atrasadas: 2,
  },
  {
    eng_id: '2',
    nome: 'Maria Santos',
    exclusivo: false,
    total_projetos: 6,
    areas_ativas: 4,
    media_percentual: 85.0,
    total_retrabalhos: 1,
    dias_trabalho_pendentes: 18,
    areas_atrasadas: 0,
  },
  {
    eng_id: '3',
    nome: 'Carlos Oliveira',
    exclusivo: true,
    total_projetos: 10,
    areas_ativas: 7,
    media_percentual: 58.0,
    total_retrabalhos: 5,
    dias_trabalho_pendentes: 35,
    areas_atrasadas: 3,
  },
]

export const mockAreas = [
  {
    area_id: '1',
    codigo: 'ELETRICO',
    descricao: 'Elétrico',
    tempo_trabalho_dias: 15,
    total_projetos: 8,
    areas_ativas: 5,
    areas_concluidas: 3,
    percentual_conclusao: 37.5,
    tem_etapas_pavimento: true,
    tem_etapas_globais: true,
  },
  {
    area_id: '2',
    codigo: 'HIDROSSANITARIO',
    descricao: 'Hidrossanitário',
    tempo_trabalho_dias: 12,
    total_projetos: 6,
    areas_ativas: 3,
    areas_concluidas: 3,
    percentual_conclusao: 50.0,
    tem_etapas_pavimento: true,
    tem_etapas_globais: true,
  },
  {
    area_id: '3',
    codigo: 'ESTRUTURAL',
    descricao: 'Estrutural',
    tempo_trabalho_dias: 20,
    total_projetos: 5,
    areas_ativas: 4,
    areas_concluidas: 1,
    percentual_conclusao: 20.0,
    tem_etapas_pavimento: true,
    tem_etapas_globais: true,
  },
  {
    area_id: '4',
    codigo: 'LIMP_ARQ',
    descricao: 'Limpeza de Arquitetura',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '5',
    codigo: 'LIMP_EST',
    descricao: 'Limpeza de Estrutura',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '6',
    codigo: 'COMPLEMENTO',
    descricao: 'Complemento',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '7',
    codigo: 'ALTERACAO_ENERGISA',
    descricao: 'Alteração Energisa',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '8',
    codigo: 'ADMINISTRATIVO',
    descricao: 'Administrativo',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '9',
    codigo: 'ENERGISA',
    descricao: 'Energisa',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '10',
    codigo: 'CALCULO_AREAS',
    descricao: 'Cálculo de Áreas',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
  {
    area_id: '11',
    codigo: 'ESTACAO_ELEVATORIA_ESGOTO',
    descricao: 'Estação Elevatória de Esgoto',
    tempo_trabalho_dias: 0,
    total_projetos: 0,
    areas_ativas: 0,
    areas_concluidas: 0,
    percentual_conclusao: 0,
    tem_etapas_pavimento: false,
    tem_etapas_globais: true,
  },
]

